import type { Core } from '@strapi/strapi';

const config: Core.Config.Middlewares = [
  'strapi::logger',
  'strapi::errors',
  {
    name: "strapi::security",
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          "connect-src": ["'self'", "https:"],
          "script-src": [
            "https://cdnjs.cloudflare.com",
            "'self'",
            'unsafe-inline',
            'https://maps.googleapis.com',
            "https://*.basemaps.cartocdn.com",
          ],
          "media-src": [
            "https://cdnjs.cloudflare.com",
            "'self'",
            "blob:",
            "data:",
            "https://tile.openstreetmap.org",
            "https://*.tile.openstreetmap.org",
            "https://*.basemaps.cartocdn.com",
            'https://maps.gstatic.com',
            'https://maps.googleapis.com',
          ],
          "img-src": [
            "https://cdnjs.cloudflare.com",
            "'self'",
            "blob:",
            "data:",
            "market-assets.strapi.io",
            "https://*.basemaps.cartocdn.com",
            "https://*.tile.openstreetmap.org",
            "https://unpkg.com/leaflet@1.9.4/dist/images/",
            'https://maps.gstatic.com',
            'https://maps.googleapis.com',
            'khmdb0.google.com',
            'khmdb0.googleapis.com',
            'khmdb1.google.com',
            'khmdb1.googleapis.com',
            'khm.google.com',
            'khm.googleapis.com',
            'khm0.google.com',
            'khm0.googleapis.com',
            'khm1.google.com',
            'khm1.googleapis.com',
            'khms0.google.com',
            'khms0.googleapis.com',
            'khms1.google.com',
            'khms1.googleapis.com',
            'khms2.google.com',
            'khms2.googleapis.com',
            'khms3.google.com',
            'khms3.googleapis.com',
            'streetviewpixels-pa.googleapis.com',
            'market-assets.strapi.io',
          ],
        },
      },
    },
  },
  'strapi::cors',
  'strapi::poweredBy',
  'strapi::query',
  'strapi::body',
  'strapi::session',
  'strapi::favicon',
  'strapi::public',
];

export default config;
